const state={config:null,products:[],categories:[],activeCategory:"todos",query:"",modalProduct:null,imageIndex:0,mascotIndex:0};
const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
async function loadJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(path);return r.json()}
function linkFor(type,product){const c=state.config.contacto;
 if(type==="whatsapp"){const text=product?`Hola, Jlias Shop.\n\nEstoy interesada en:\nProducto: ${product.nombre}\nCódigo: ${product.codigo}\nPrecio: $${product.precio}\n\n¿Podrían indicarme la disponibilidad actual, colores y cómo realizar el pedido?`:`Hola, Jlias Shop. Me gustaría recibir información sobre sus productos y disponibilidad.`;return `https://wa.me/${c.whatsappNumero}?text=${encodeURIComponent(text)}`}
 if(type==="canalWhatsapp")return c.canalWhatsapp;if(type==="instagram")return c.instagram;if(type==="tiktok")return c.tiktok;if(type==="catalogo")return "#catalogo";return "#"}
function setupConfig(){const c=state.config;
 $("#headerWhatsapp").href=linkFor("whatsapp");$("#heroChannel").href=linkFor("canalWhatsapp");$("#channelButton").href=linkFor("canalWhatsapp");$("#aboutWhatsapp").href=linkFor("whatsapp");
 $("#footerInstagram").href=linkFor("instagram");$("#footerTiktok").href=linkFor("tiktok");$("#footerChannel").href=linkFor("canalWhatsapp");$("#footerWhatsapp").href=linkFor("whatsapp");$("#footerWhatsapp").textContent=c.contacto.whatsappVisible;
 $("#floatingWhatsapp").onclick=()=>window.open(linkFor("whatsapp"),"_blank");
 if(c.anuncio.activo&&!sessionStorage.getItem("jliasAnnouncementClosed")){$("#announcement").hidden=false;$("#announcementText").textContent=c.anuncio.texto;$("#announcementButton").textContent=c.anuncio.boton;$("#announcementLink").href=linkFor(c.anuncio.enlace)}
 $("#announcementClose").onclick=()=>{$("#announcement").hidden=true;sessionStorage.setItem("jliasAnnouncementClosed","1")};
 $("#year").textContent=new Date().getFullYear()}
function renderCategories(){const countBy={};state.products.forEach(p=>countBy[p.categoria]=(countBy[p.categoria]||0)+1);
 $("#categoryCards").innerHTML=state.categories.filter(c=>c.id!=="todos").map(c=>`<article class="category-card" data-category="${c.id}"><img src="${c.imagen}" alt="${c.nombre}" loading="lazy"><div><h3>${c.nombre}</h3><span>${countBy[c.id]||0} productos</span></div></article>`).join("");
 $("#filterBar").innerHTML=state.categories.map(c=>`<button class="filter-btn ${c.id==="todos"?"active":""}" data-filter="${c.id}">${c.nombre}</button>`).join("");
 $$(".category-card").forEach(x=>x.onclick=()=>selectCategory(x.dataset.category));
 $$(".filter-btn").forEach(x=>x.onclick=()=>selectCategory(x.dataset.filter));
 $$("[data-category-link]").forEach(x=>x.onclick=()=>selectCategory(x.dataset.categoryLink))}
function productCard(p){return `<article class="product-card">${p.destacado?'<span class="badge">DESTACADO</span>':""}<div class="product-image" data-open="${p.codigo}"><img src="${p.imagenes[0]}" alt="${p.nombre}" loading="lazy"></div><div class="product-copy"><h3>${p.nombre}</h3><p class="price">$${p.precio}</p><div class="card-actions"><button data-open="${p.codigo}">Ver detalles</button><a href="${linkFor("whatsapp",p)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`}
function renderProducts(){const filtered=state.products.filter(p=>(state.activeCategory==="todos"||p.categoria===state.activeCategory)&&(`${p.nombre} ${p.codigo} ${p.categoria}`.toLowerCase().includes(state.query)));
 $("#productGrid").innerHTML=filtered.map(productCard).join("");$("#resultCount").textContent=`${filtered.length} producto${filtered.length===1?"":"s"}`;$("#emptyState").hidden=filtered.length>0;
 $("#featuredGrid").innerHTML=state.products.filter(p=>p.destacado).slice(0,8).map(productCard).join("");
 $$("[data-open]").forEach(x=>x.onclick=()=>openModal(x.dataset.open))}
function selectCategory(id){state.activeCategory=id;$$(".filter-btn").forEach(x=>x.classList.toggle("active",x.dataset.filter===id));renderProducts();setTimeout(()=>$("#catalogo").scrollIntoView({behavior:"smooth"}),50)}
function openModal(code){const p=state.products.find(x=>x.codigo===code);if(!p)return;state.modalProduct=p;state.imageIndex=0;updateModal();$("#productModal").hidden=false;document.body.classList.add("modal-open")}
function updateModal(){const p=state.modalProduct;$("#modalCode").textContent=p.codigo+" · "+p.categoria;$("#modalTitle").textContent=p.nombre;$("#modalPrice").textContent=`$${p.precio}`;$("#modalDescription").textContent=p.descripcion;$("#modalImage").src=p.imagenes[state.imageIndex];$("#modalImage").alt=p.nombre;$("#modalWhatsapp").href=linkFor("whatsapp",p);$("#modalChannel").href=linkFor("canalWhatsapp");$("#galleryDots").innerHTML=p.imagenes.map((_,i)=>`<button class="${i===state.imageIndex?"active":""}" data-dot="${i}" aria-label="Ver imagen ${i+1}"></button>`).join("");$$("[data-dot]").forEach(x=>x.onclick=()=>{state.imageIndex=+x.dataset.dot;updateModal()})}
function closeModal(){$("#productModal").hidden=true;document.body.classList.remove("modal-open")}
function setupModal(){$$("[data-close-modal]").forEach(x=>x.onclick=closeModal);$("#prevImage").onclick=()=>{const n=state.modalProduct.imagenes.length;state.imageIndex=(state.imageIndex-1+n)%n;updateModal()};$("#nextImage").onclick=()=>{const n=state.modalProduct.imagenes.length;state.imageIndex=(state.imageIndex+1)%n;updateModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()})}
function setupMascot(){const m=state.config.mascota;if(!m.activa||sessionStorage.getItem("jliasMascotClosed"))return;setTimeout(()=>{showMascot();setInterval(showMascot,m.intervalo)},m.retrasoInicial);$("#mascotClose").onclick=()=>{$("#mascotWidget").hidden=true;sessionStorage.setItem("jliasMascotClosed","1")}}
function showMascot(){if(sessionStorage.getItem("jliasMascotClosed"))return;const arr=state.config.mascota.mensajes,msg=arr[state.mascotIndex%arr.length];state.mascotIndex++;$("#mascotText").textContent=msg.texto;$("#mascotAction").textContent=msg.boton;$("#mascotAction").href=linkFor(msg.enlace);$("#mascotAction").target=msg.enlace==="catalogo"?"_self":"_blank";$("#mascotWidget").hidden=false}
async function init(){try{[state.config,state.products,state.categories]=await Promise.all([loadJSON("data/config.json"),loadJSON("data/productos.json"),loadJSON("data/categorias.json")]);setupConfig();renderCategories();renderProducts();setupModal();setupMascot();$("#searchInput").oninput=e=>{state.query=e.target.value.trim().toLowerCase();renderProducts()};$("#menuToggle").onclick=()=>$("#mainNav").classList.toggle("open");$("#mainNav").onclick=()=>$("#mainNav").classList.remove("open")}catch(e){document.body.innerHTML=`<main style="padding:40px;font-family:sans-serif"><h1>Jlias Shop</h1><p>Para visualizar el catálogo, abre esta carpeta desde un servidor web. Consulta README.md.</p></main>`;console.error(e)}}
init();