const state={config:null,products:[],categories:[],activeCategory:'todos',activeSubcategory:'todos',query:'',modalProduct:null,imageIndex:0,mascotIndex:0,slideIndex:0,slideTimer:null,mascotTimer:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const normalize=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
async function loadJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
function safe(id,fn){const el=$(id);if(el)fn(el);return el}
function linkFor(type,p){const c=state.config.contacto;if(type==='whatsapp'){const text=p?`Hola, Jlia’s Shop.\n\nEstoy interesada en este producto:\n\nProducto: ${p.nombre}\nCódigo: ${p.codigo}\nPrecio: $${p.precio}\n\n¿Podrían indicarme disponibilidad?`:`Hola, Jlia’s Shop.\n\nEstoy revisando su catálogo y quisiera recibir información sobre productos y disponibilidad.`;return `https://wa.me/${c.whatsappNumero}?text=${encodeURIComponent(text)}`}if(type==='grupoWhatsapp')return c.grupoWhatsapp;if(type==='instagram')return c.instagram;if(type==='tiktok')return c.tiktok;if(type==='catalogo')return '#catalogo';return '#'}
function setupConfig(){
 ['headerWhatsapp','aboutWhatsapp','footerWhatsapp'].forEach(id=>safe('#'+id,e=>e.href=linkFor('whatsapp')));
 ['heroGroup','footerGroup'].forEach(id=>safe('#'+id,e=>e.href=linkFor('grupoWhatsapp')));
 safe('#footerInstagram',e=>e.href=linkFor('instagram'));safe('#footerTiktok',e=>e.href=linkFor('tiktok'));
 safe('#footerWhatsapp',e=>e.textContent=state.config.contacto.whatsappVisible);
 const a=state.config.anuncio||{};const closed=sessionStorage.getItem('jliasAnnouncementClosed');
 safe('#announcement',e=>e.hidden=!a.activo||!!closed);safe('#announcementText',e=>e.textContent=a.texto||'');safe('#announcementButton',e=>e.textContent=a.boton||'');safe('#announcementLink',e=>e.href=linkFor(a.enlace||'tiktok'));
 safe('#announcementClose',e=>e.onclick=()=>{safe('#announcement',x=>x.hidden=true);sessionStorage.setItem('jliasAnnouncementClosed','1')});
 safe('#year',e=>e.textContent=new Date().getFullYear());
}
function productCard(p){return `<article class="product-card"><button class="product-image" type="button" data-open="${p.codigo}" aria-label="Ver ${p.nombre}">${p.destacado?'<span class="badge">Destacado</span>':''}<img src="${p.imagenes[0]}" alt="${p.nombre}" loading="lazy"><span class="photo-count">📷 ${p.imagenes.length}</span></button><div class="product-copy"><span class="product-type">${p.subcategoria||p.categoria}</span><h3>${p.nombre}</h3><p class="price">$${p.precio}</p><div class="card-actions"><button type="button" data-open="${p.codigo}">Ver ${p.imagenes.length>1?'fotos':'detalle'}</button><a href="${linkFor('whatsapp',p)}" target="_blank" rel="noopener">Consultar</a></div></div></article>`}
function renderCategories(){safe('#categoryCards',el=>el.innerHTML=state.categories.filter(c=>c.id!=='todos').map(c=>`<button type="button" class="category-card" data-category="${c.id}" aria-label="Abrir ${c.nombre}"><img src="${c.imagen}" alt="${c.nombre}" loading="lazy"><div><h3>${c.nombre}</h3></div></button>`).join(''));safe('#filterBar',el=>el.innerHTML=state.categories.map(c=>`<button type="button" class="filter-btn ${c.id==='todos'?'active':''}" data-filter="${c.id}">${c.nombre}</button>`).join(''))}
function renderFeatured(){const codes=state.config.destacados||[];let items=codes.map(code=>state.products.find(p=>p.codigo===code)).filter(Boolean);if(items.length<4)items=state.products.filter(p=>p.destacado).slice(0,4);safe('#featuredGrid',el=>el.innerHTML=items.slice(0,4).map(productCard).join(''))}
function renderSubfilters(){const bar=$('#subFilterBar');if(!bar)return;if(state.activeCategory==='todos'){bar.hidden=true;bar.innerHTML='';return}const subs=[...new Set(state.products.filter(p=>p.categoria===state.activeCategory).map(p=>p.subcategoria).filter(Boolean))];if(subs.length<2){bar.hidden=true;bar.innerHTML='';return}bar.hidden=false;bar.innerHTML=`<button class="sub-filter-btn ${state.activeSubcategory==='todos'?'active':''}" data-subfilter="todos">Todos</button>`+subs.map(s=>`<button class="sub-filter-btn ${state.activeSubcategory===s?'active':''}" data-subfilter="${s}">${s}</button>`).join('')}
function matches(p,q){const hay=normalize(`${p.nombre} ${p.categoria} ${p.subcategoria||''} ${p.codigo} ${p.descripcion||''} ${(p.palabrasClave||[]).join(' ')}`);return normalize(q).split(' ').filter(Boolean).every(t=>hay.includes(t)||(t==='leggin'&&hay.includes('legging')))}
function renderProducts(){let list=state.products.filter(p=>p.estado==='Activo');if(state.activeCategory!=='todos')list=list.filter(p=>p.categoria===state.activeCategory);if(state.activeSubcategory!=='todos')list=list.filter(p=>p.subcategoria===state.activeSubcategory);if(state.query)list=list.filter(p=>matches(p,state.query));safe('#productGrid',el=>el.innerHTML=list.map(productCard).join(''));safe('#resultCount',el=>el.textContent=`${list.length} producto${list.length===1?'':'s'} disponibles`);safe('#emptyState',el=>el.hidden=!!list.length);renderSubfilters();$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.activeCategory));safe('#catalogTitle',el=>el.textContent=state.activeCategory==='todos'?'Todo para completar tu look':state.activeCategory);safe('#catalogSubtitle',el=>el.textContent=state.activeSubcategory==='todos'?'':`Colección: ${state.activeSubcategory}`);safe('#backToCategories',el=>el.hidden=state.activeCategory==='todos');safe('#showAllTop',el=>el.hidden=state.activeCategory==='todos')}
function revealCatalog(){safe('#catalogo',el=>el.hidden=false)}
function selectCategory(cat,scroll=true){state.activeCategory=cat;state.activeSubcategory='todos';state.query='';safe('#searchInput',e=>e.value='');revealCatalog();renderProducts();if(scroll)safe('#catalogo',e=>e.scrollIntoView({behavior:'smooth',block:'start'}))}
function showAll(){selectCategory('todos')}
function searchFromHome(value){state.activeCategory='todos';state.activeSubcategory='todos';state.query=normalize(value);safe('#searchInput',e=>e.value=value);revealCatalog();renderProducts();safe('#catalogo',e=>e.scrollIntoView({behavior:'smooth',block:'start'}))}
function updateGallery(){const p=state.modalProduct;if(!p)return;safe('#modalImage',e=>e.src=p.imagenes[state.imageIndex]);safe('#galleryCounter',e=>e.textContent=`${state.imageIndex+1} / ${p.imagenes.length}`);safe('#galleryDots',e=>e.innerHTML=p.imagenes.map((_,i)=>`<button class="${i===state.imageIndex?'active':''}" data-dot="${i}" aria-label="Imagen ${i+1}"></button>`).join(''));safe('#prevImage',e=>e.hidden=p.imagenes.length<2);safe('#nextImage',e=>e.hidden=p.imagenes.length<2)}
function openModal(code){const p=state.products.find(x=>x.codigo===code);if(!p)return;state.modalProduct=p;state.imageIndex=0;safe('#modalCode',e=>e.textContent=`${p.codigo} · ${p.categoria} · ${p.subcategoria||''}`);safe('#modalTitle',e=>e.textContent=p.nombre);safe('#modalPrice',e=>e.textContent=`$${p.precio}`);safe('#modalDescription',e=>e.textContent=p.descripcion);safe('#modalWhatsapp',e=>e.href=linkFor('whatsapp',p));safe('#modalGroup',e=>e.href=linkFor('grupoWhatsapp'));updateGallery();safe('#productModal',e=>e.hidden=false);document.body.classList.add('modal-open');safe('#mascotWidget',e=>e.hidden=true)}
function closeModal(){safe('#productModal',e=>e.hidden=true);document.body.classList.remove('modal-open');if(!sessionStorage.getItem('jliasMascotClosed'))safe('#mascotWidget',e=>e.hidden=false)}
function setupMascot(){const cfg=state.config.mascota||{};const msgs=cfg.mensajes||[];if(!cfg.activa||!msgs.length){safe('#mascotWidget',e=>e.hidden=true);return}const show=()=>{const m=msgs[state.mascotIndex++%msgs.length];safe('#mascotText',e=>e.textContent=m.texto);safe('#mascotAction',e=>{e.textContent=m.boton;e.href=linkFor(m.enlace||m.accion);e.target=m.enlace==='catalogo'?'_self':'_blank'})};show();if(!sessionStorage.getItem('jliasMascotClosed'))setTimeout(()=>safe('#mascotWidget',e=>e.hidden=false),cfg.retrasoInicial||1200);clearInterval(state.mascotTimer);state.mascotTimer=setInterval(show,cfg.intervalo||9000);safe('#mascotClose',e=>e.onclick=()=>{safe('#mascotWidget',x=>x.hidden=true);sessionStorage.setItem('jliasMascotClosed','1')})}
function setupSlider(){const cfg=state.config.carousel||{};const imgs=cfg.imagenes||[];if(!cfg.activo||!imgs.length)return;const track=$('#sliderTrack');if(!track)return;track.innerHTML=imgs.map((src,i)=>`<div class="slider-slide"><img src="${src}" alt="Inspiración Jlia’s Shop ${i+1}" loading="lazy"></div>`).join('');safe('#sliderDots',e=>e.innerHTML=imgs.map((_,i)=>`<button data-slide="${i}" class="${i===0?'active':''}" aria-label="Ir a imagen ${i+1}"></button>`).join(''));const go=i=>{state.slideIndex=(i+imgs.length)%imgs.length;track.style.transform=`translateX(-${state.slideIndex*100}%)`;$$('[data-slide]').forEach((d,j)=>d.classList.toggle('active',j===state.slideIndex))};const reset=()=>{clearInterval(state.slideTimer);state.slideTimer=setInterval(()=>go(state.slideIndex+1),cfg.intervalo||3500)};safe('#sliderPrev',e=>e.onclick=()=>{go(state.slideIndex-1);reset()});safe('#sliderNext',e=>e.onclick=()=>{go(state.slideIndex+1);reset()});safe('#sliderDots',e=>e.onclick=ev=>{const d=ev.target.closest('[data-slide]');if(d){go(+d.dataset.slide);reset()}});go(0);reset()}
function setupEvents(){document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){e.preventDefault();selectCategory(cat.dataset.category);return}const f=e.target.closest('[data-filter]');if(f){e.preventDefault();selectCategory(f.dataset.filter);return}const sf=e.target.closest('[data-subfilter]');if(sf){state.activeSubcategory=sf.dataset.subfilter;renderProducts();return}const op=e.target.closest('[data-open]');if(op){e.preventDefault();openModal(op.dataset.open);return}const dot=e.target.closest('[data-dot]');if(dot){state.imageIndex=+dot.dataset.dot;updateGallery();return}if(e.target.closest('[data-close-modal]')){closeModal();return}if(e.target.closest('[data-show-all]')){e.preventDefault();showAll();return}});safe('#searchInput',e=>e.addEventListener('input',ev=>{state.query=normalize(ev.target.value);renderProducts()}));safe('#homeSearchInput',e=>{e.addEventListener('input',ev=>{if(ev.target.value.trim().length>=2)searchFromHome(ev.target.value)});e.addEventListener('keydown',ev=>{if(ev.key==='Enter')searchFromHome(ev.target.value)})});safe('#openAllProducts',e=>e.onclick=showAll);safe('#backToCategories',e=>e.onclick=()=>safe('#categorias',x=>x.scrollIntoView({behavior:'smooth'})));safe('#showAllTop',e=>e.onclick=showAll);safe('#prevImage',e=>e.onclick=()=>{state.imageIndex=(state.imageIndex-1+state.modalProduct.imagenes.length)%state.modalProduct.imagenes.length;updateGallery()});safe('#nextImage',e=>e.onclick=()=>{state.imageIndex=(state.imageIndex+1)%state.modalProduct.imagenes.length;updateGallery()});safe('#menuToggle',e=>e.onclick=()=>{const n=$('#mainNav');if(!n)return;n.classList.toggle('open');e.setAttribute('aria-expanded',n.classList.contains('open'))});$$('.secondary-nav a').forEach(a=>a.onclick=()=>safe('#mainNav',n=>n.classList.remove('open')));safe('#scrollTop',e=>e.onclick=()=>window.scrollTo({top:0,behavior:'smooth'}));window.addEventListener('scroll',()=>{safe('#scrollTop',e=>e.classList.toggle('visible',scrollY>260));safe('#mascotWidget',e=>e.classList.toggle('minimized',scrollY>420))})}
async function init(){try{[state.config,state.products,state.categories]=await Promise.all([loadJSON('data/config.json'),loadJSON('data/productos.json'),loadJSON('data/categorias.json')]);setupConfig();renderCategories();renderFeatured();setupSlider();setupEvents();setupMascot();window.__JLIAS_READY__=true}catch(err){console.error('JLIAS INIT ERROR',err);safe('#catalogo',e=>e.hidden=false);safe('#resultCount',e=>e.textContent='No se pudo cargar el catálogo. Recarga la página.');window.__JLIAS_ERROR__=String(err)}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
